name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say Hello
        run: echo "Hello World!"
  printDate_job:
    runs-on: ubuntu-20.04
    steps: 
      - name: print Date
        run: |
          now=$(date)
          echo $now
  printDir_job:
      runs-on: ubuntu-20.04
      steps:
        - name: print directory
          run: ls -l

          