name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{toJson(github.event.commits.*.message)}}
          CHECK: ${{contains(github.event.head_commit.message, '#skip')}}
          # if: 
          # COMMIT_MESSAGES: ${{toJson(github.event.commits.*.message)}}
        # run: echo "$COMMIT_MESSAGES"
        run: echo "$CHECK"

  #  COMMIT_MESSAGES: ${{contains(toJson(github.event.commits.*.message, '#skip'))}}